# Generated by Django 5.0.4 on 2024-05-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalpath', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='level',
            table='personalpath_level',
        ),
    ]
