# Generated by Django 5.0.4 on 2024-05-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0004_course_category_course_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('data_science', 'Data Science'), ('design', 'Design'), ('security', 'Security')], default='programming', max_length=20),
        ),
    ]
