# Generated by Django 5.0.4 on 2024-06-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0006_alter_course_category'),
        ('CourseApp', '0007_course_link'),
    ]

    operations = [
    ]
