# Generated by Django 5.0.4 on 2024-05-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'User'), ('instructor', 'Instructor')], default='user', max_length=20),
        ),
    ]
